config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'
  
  match '/help',          to: 'static_pages#help',    via: 'get'
  match '/home',          to: 'static_pages#home',    via: 'get'
  match '/dev',           to: 'static_pages#dev',     via: 'get'
  match 'debtor/search',  to: 'debtors#search',       via: 'get', as: 'search'
  
  match '/import',        to: 'import#create',        via: 'post'
  match '/import',        to: 'import#new',           via: 'get'
  match '/import/status', to: 'import#status',        via: 'get'
  
  match '/email',         to: 'debts#preview_email',  via: 'get'
  match '/email/send',    to: 'debts#send_email',     via: 'post' 

  resources :debtors 
  resources :debts, except: :destroy do 
    resources :mail_logs, except: :destroy
  end

  match '/letter',        to: 'static_pages#modeloSC_724', via: 'get'
  
  

end

app/models/debtor.rb
# -*- encoding : utf-8 -*-

require 'HexString'

# rubocop:disable Metrics/LineLength
class Debtor < ActiveRecord::Base
  has_many :debts, dependent: :restrict_with_exception

  ## Hooks
  before_save { self.email = email.downcase if email }
  before_save { self.ss_last_four = last_four(ss_hex_digest) unless ss_hex_digest.blank? }
  before_save { self.uses_personal_ss = true unless ss_hex_digest.blank? }
  before_save { self.contact_person_email = email.downcase if email }
  before_save do
    self.ss_hex_digest = unless ss_hex_digest.blank?
                           Debtor.encrypt(ss_hex_digest)
                         end
  end
  # TODO: before save: clean up telephone number and ss
  before_save do
    self.tel = Debtor.remove_hyphens(tel) if tel
  end
  # TODO: before save can clean up telephone number by selecting only [[:digits:]]
  # TODO alter tel regex to accept parenthesis and spaces
  # before_save record_transaction

  ## REGEX
  VALID_EMAIL_REGEX = /\A(\z|[\w+\-.]+@[a-z\d\-.]+\.[a-z]+)\z/i
  VALID_TEL_REGEX = /\A(\z|([0-9]{3}-?[0-9]{3}-?[0-9]{4}))\z/
  VALID_EIN_REGEX = /\A(\z|([0-9]{2})-?([0-9]{7}))\z/
  VALID_SS_REGEX = /\A(\z|([0-9]{3}-?[0-9]{2}-?[0-9]{4}))\z/
  VALID_DATE_REGEX = //

  ## Validations
  validates :name,                presence: true
  validates :contact_person,      presence: true
  validates :email,                format: { with: VALID_EMAIL_REGEX,
                                             message: 'Email invalido'  }
  validates :contact_person_email, format: { with: VALID_EMAIL_REGEX,
                                             message: 'Email invalido'  }
  validates :tel, format: { with: VALID_TEL_REGEX,
                            message: "Debe de der un número de teléfono válido: 'xxx-xxx-xxx'" }
  validates :employer_id_number, absence: true,
                                 unless: proc { |debtor_ex| debtor_ex.ss_hex_digest.blank? }
  validates :ss_hex_digest, absence: true,
                            unless: proc { |debtor_ex| debtor_ex.employer_id_number.blank? }
  validates :employer_id_number,  uniqueness: true,
                                  unless: proc { |debtor_ex| debtor_ex.employer_id_number.blank? }
  validates :ss_hex_digest,       uniqueness: true,
                                  unless: proc { |debtor_ex| debtor_ex.ss_hex_digest.blank? }
  validates :employer_id_number,  format: { with: VALID_EIN_REGEX,
                                            message: "El Número de Seguro Social Patronal debe de ser válido: 'xx-xxxxxxx' o en blanco." }
  validates :ss_hex_digest,       format: { with: VALID_SS_REGEX,
                                            message: "El Número de Seguro Social Personal debe de ser válido: 'xx-xxx-xxxx' o en blanco." }

  ## Methods
  def self.search(search_term)
    search_term = clean_up_search_term(search_term)
    term_class = search_term.class

    if term_class == Integer
      where('employer_id_number LIKE ?', "%#{search_term}%")
    elsif term_class == HexString # For API
      where('ss_hex_digest LIKE ?', "%#{search_term}%")
    elsif term_class == String
      where('LOWER(name) LIKE ? OR employer_id_number LIKE ? OR email LIKE ?',
            "%#{search_term}%", "%#{search_term}%", "%#{search_term}%")
    else
      fail 'search term of unknown type (find me in debtor model)'
    end
  end

  def self.clean_up_search_term(search_term)
    # if name keep string, if ein turn to int, if ss turn to hexstring else string
    # '-' is checked.
    case search_term
    when /\A([[:digit:]]{3}-[[:digit:]]{2}-[[:digit:]]{4})\z/
      HexString.new(Debtor.encrypt(search_term)) # or Encrypt(search_term)
    when /\A([0-9]{2}-[0-9]{7})\z/ # REGEX for EIN
      Debtor.remove_hyphens(search_term).to_i
    when /\A[[:xdigit:]]+\z/i
      HexString.new search_term.to_s.downcase
    else
      search_term.to_s.downcase
    end
  end

  def last_four(ss_num)
    Debtor.remove_hyphens(ss_num).split('')[-4..-1].join('')
  end

  def self.remove_hyphens(term)
    term.to_s.each_char.select { |x| x.match(/[0-9]/) }.join('')
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(Debtor.salt(Debtor.remove_hyphens(token)).to_s)
  end

  def self.salt(token, salt = Rails.application.secrets.salt)
    # salt stored in secrets.yml
    fail(ArgumentError, 'Nil propagation, token not set', caller) if token.nil?
    fail(ArgumentError, 'Rails Salt (config/secret.yml) not set', caller) if salt.nil?
    token.to_i + salt
  end

  def self.guard_length(token, length = 9) # should be in lib
    fail unless token.to_s.split('').size == length
  end
end

app/controllers/debtors_controller.rb
# -*- encoding : utf-8 -*-

class DebtorsController < ApplicationController
  before_action :authenticate_user! ## for DEVISE
  # before_destroy current_user.user_role.somethingsomething

  ## Resource Actions ##
  def new
    assign_current_user
    @debtor = Debtor.new
  end

  def create
    assign_current_user
    @debtor = Debtor.new(debtor_params)
    begin
      if @debtor.save
        flash[:success] = 'Nuevo Record de Deudor Creado.'
        redirect_to @debtor
      else
        flash.now[:warning] = 'Hubo un Error. Record de Deudor No Creado.'
        render 'new'
      end
    rescue ActiveRecord::RecordNotUnique, ActiveRecord::StatementInvalid, ActiveRecord::JDBCError => e
      flash.now[:error] = "Error: Hay un problema con la data sometida. \t#{e.message}"
      render 'new'
    end
  end

  def show
    assign_current_user
    @debtor = Debtor.find(params[:id]) # Should this be find_by_id?
    # cookies[:current_debtor_id] = @debtor.id
    # @collections = @debtor.collections.paginate(page: params[:page])
  end

  def destroy
    assign_current_user # Should only be certain users --> Supervisor users.
    # With 'dependency: restrict' only debtors w/ no debt can be deleted.
    begin
      Debtor.find(params[:id]).destroy
      flash[:success] = 'Record del deudor borrado.'
    rescue ActiveRecord::DeleteRestrictionError => e
      flash[:error] = e
      raise e
    end
    redirect_to debtors_url
  end

  def edit
    assign_current_user
    @debtor = Debtor.find(params[:id])
  end

  def update
    # TODO: fix form method to patch or put for SS
    # Probably related to debtor_params below
    assign_current_user
    @debtor = Debtor.find(params[:id])
    begin
      if @debtor.update_attributes(debtor_params)
        flash[:success] = 'Informacion del deudor actualizada.'
        redirect_to @debtor
      else
        render 'edit'
      end
    rescue ActiveRecord::RecordNotUnique, ActiveRecord::StatementInvalid, ActiveRecord::JDBCError => e
      flash.now[:error] = "Error: Hay un problema con la data sometida. \t#{e.message}"
      render 'new'
    end
  end

  def index
    assign_current_user

    @debtors =
      if params[:search].blank?
        Debtor.paginate(page: params[:page], per_page: 10)
      else
        Debtor.search(params[:search])
      end

    @color_code_proc =
      lambda do |debtor_debts|
        debtor_debts
          .collect { |debt| debt.paid_in_full ? 0 : debt.amount_owed_pending_balance }
          .reduce(0) { |total, amount| amount + total }
      end
  end

  ## Additional Methods ##
  def search
    @debtor = Debtor.search(params[:search])
  end

  ## API Search Stub for integration with other systems
  # TODO Add security and finalize
  def api_search
    # TODO: add a limit to the debtor info sent by json.
    respond_to do |format|
      format.html
      format.json { render json: @debtor, callback: params[:callback] }
    end
    @debtor = Debtor.api_search(params[:search])
  end

  private

  def assign_current_user
    @user = current_user
  end

  def debtor_params
    if user_signed_in? # updated for Devise
      # Can be determined by role
      # TODO add last SS permit and logic above
      params.require(:debtor).permit(:name, :email, :tel, :ext, :address,
                                     :location,
                                     :contact_person,
                                     :contact_person_email,
                                     :employer_id_number,
                                     :ss_hex_digest)
    else
      redirect_to new_user_session_path
    end
  end
end

app/helpers/debtors_helper.rb
# -*- encoding : utf-8 -*-

module DebtorsHelper
end

app/views/debtors/_debtor.html.haml
- (total = @color_code_proc.call(debtor.debts)) unless debtor.nil?
%li{:class => "#{total.zero? ? 'green' : 'red' } round-bottom-corners debtors"}
  -# Create a collect method to show total amount owed or paid.{:class => "#{debtor.collections.any? ? 'red' : 'green'}"}
  = "#{debtor.id}"
  = " "
  %strong
    = link_to(("<span class='glyphicon glyphicon-folder-open'></span> ".html_safe + debtor.name), debtor)
  = " - "
  -#= debtor.tel
  -#= debtor.ext
  = debtor.email
  = " | " unless debtor.employer_id_number.blank?
  = link_to debtor.employer_id_number, debtor 
  - if total.zero?
    = " | #{number_to_currency total, :unit => "$"}"
  - else
    = " | <strong>".html_safe + number_to_currency(total, :unit => '$') + "</strong>".html_safe
  - unless true or debtor.respond_to?(:debts) && !debtor.debts.blank?#current_user.admin? #or current_user.supervisor?
    = " | "
    = link_to "<span class='glyphicon glyphicon-trash'></span> delete".html_safe, debtor, method: :delete, data: {confirm: "Confirme Borrar Record: ¿Seguro?"}

app/views/debtors/edit.html.haml
- provide(:title, "Editar Record del Deudor")
%h1.col-md-offset-2 Editar Record del Deudor 
.row
  -if @debtor.errors.any?
    %p.col-md-8.col-md-offset-2
      %strong
        Problemas con:
    - @debtor.errors.full_messages.each do |msg|
      %li{:class => "alert alert-danger col-md-8 col-md-offset-2"}
        = msg
  /
  %div{:class => "col-md-8 col-md-offset-2"}
    =form_for(@debtor, :method => 'patch') do |f|
      -# Is this partial below duplicating errors?
      =# render partial: 'layouts/error_messages', :locals => { :object => f.object }
      =f.label :name, "Nombre"
      =f.text_field :name, class: 'form-control'
      =f.label :email, "Email"
      =f.email_field :email, class: 'form-control'
      =f.label :tel, "Teléfono"
      =f.telephone_field :tel, class: 'form-control', placeholder: 'ex. 787-555-1234'
      =f.label :ext, "Extención"
      =f.telephone_field :ext
      =f.label :address, "Dirección Postal"
      =f.text_field :address, class: 'form-control'
      =f.label :location, "Dirección Física"
      =f.text_field :location, class: 'form-control'
      =f.label :contact_person, "Persona Contácto"
      =f.text_field :contact_person, class: 'form-control'
      =f.label :contact_person_email, "Email de la Persona Contácto"
      =f.email_field :contact_person_email, class: 'form-control'
      =f.label :employer_id_number, "Numbero de SS Patronal"
      =f.text_field :employer_id_number, class: 'form-control', placeholder: 'ex. 12-1234567'
      =f.label :ss_hex_digest, "Numbero de SS Personal"
      =f.text_field :ss_hex_digest, class: 'form-control', placeholder: 'ex. 123-12-1234'
      .btn-group
        =f.submit "Actualizar Record del Deudor", class: "btn btn-large btn-primary"

app/views/debtors/index.html.haml
- provide(:title, "Lista de Deudores")

= form_tag debtors_path, :method => 'get' do
  -# debtors_path might not be best?
  %p
    = search_field_tag :search, params[:search]
    .btn-group 
      = submit_tag "Buscar", :name => nil, :class => 'btn' 
  -#end
-# "Search Params? #{!params[:search].nil?}"
-# "Debtor #{@debtors.empty?}"
%h1 Lista de Deudores
-if params[:search].blank?
  - #will_paginate

  %ul.debtors
    = render @debtors
    /

  = will_paginate @debtors
-elsif @debtors.empty?
  %h4="No hay resultados para: #{params[:search]}" 
-else
  %h4="Resultados para: #{params[:search]}" 
  %ul.debtors
    = render @debtors
/

app/views/debtors/new.html.haml
- provide(:title, "Crear Record de Deudor")
%h1.col-md-offset-2 Crear Record de Deudor Nuevo
.row
  -if @debtor.errors.any?
    %p.col-md-8.col-md-offset-2
      %strong
        Problemas con:
    - @debtor.errors.full_messages.each do |msg|
      %li{:class => "alert alert-danger col-md-8 col-md-offset-2"}
        = msg
  /
  %div{:class => "col-md-8 col-md-offset-2"}
    =form_for(@debtor) do |f|
      -# Is this partial below duplicating errors?
      =# render partial: 'layouts/error_messages', :locals => { :object => f.object }
      =f.label :name, "Nombre"
      =f.text_field :name, class: 'form-control'
      =f.label :email, "Email"
      =f.email_field :email, class: 'form-control'
      =f.label :tel, "Teléfono"
      =f.telephone_field :tel, class: 'form-control', placeholder: 'ex. 787-555-1234'
      =f.label :ext, "Extención"
      =f.text_field :ext, class: 'form-control'
      =f.label :address, "Dirección Postal"
      =f.text_field :address, class: 'form-control'
      =f.label :location, "Dirección Física"
      =f.text_field :location, class: 'form-control'
      =f.label :contact_person, "Persona Contácto"
      =f.text_field :contact_person, class: 'form-control'
      =f.label :contact_person_email, "Email de la Persona Contácto"
      =f.email_field :contact_person_email, class: 'form-control'
      =f.label :employer_id_number, "Numbero de SS Patronal"
      =f.text_field :employer_id_number, class: 'form-control', placeholder: 'ex. 12-1234567'
      =f.label :ss_hex_digest, "Numbero de SS Personal"
      =f.text_field :ss_hex_digest, class: 'form-control', placeholder: 'ex. 123-12-1234'
      %br
      .btn-group
        =f.submit "Crear Record de Deudor Nuevo", class: "btn btn-large btn-primary"
  /end  
-if false #TODO #@user.user_roles.developer
  / .row
  /   %a{:href => "#{'url_for import_path'}", :class => "btn btn-large btn-info"}
  /     Importar CSV (todavia)

app/views/debtors/search.html.haml
- provide(:title, "Buscar")

= form_tag debtors_path, :method => 'get' do
  -# debtors_path might not be best?
  %p{:class => 'col-md-8_'}
    = search_field_tag :search, params[:search]
    .btn-group 
      = submit_tag "Buscar", :name => nil, :class => 'btn' 

-#end

app/views/debtors/show.html.haml
- provide(:title, "Record del Deudor")
%h1 Record del Deudor:
.row
  %aside.col-md-6
    %section
      %h1
        = @debtor.name
        %br
    %section
      .table-responsive
        %table.table-bordered.table-striped
          %thead
            %tr
              %td.grey
                Email:
              %td.grey.span4
                = @debtor.email
            %tr
              %td
                Teléfono:
              %td
                = "#{@debtor.tel} #{@debtor.ext}"
            %tr
              %td
                = @debtor.employer_id_number.blank? ? "SS -xxxx": "EIN"
              %td
                = @debtor.employer_id_number.blank? ? @debtor.ss_last_four : @debtor.employer_id_number
            %tr
              %td.grey
                Persona Contácto
              %td.grey
                = @debtor.contact_person
            %tr
              %td
                Email de la Persona Contácto
              %td
                = @debtor.contact_person_email             
  %aside.col-md-4
    %h1
    %section
      .table-responsive
        %table.table-bordered
          %thead
            %tr
              %th.col-md-1.grey
                Dirección Postal
              %td.col-md-1.grey
                = @debtor.address
          %tbody  
            %tr
              %th.col-md-1
                Dirección Física
              %td.col-md-1
                = @debtor.location
      %p
        = link_to "<span class='glyphicon glyphicon-pencil'></span> Editar Record del Deudor".html_safe, edit_debtor_path  
        
%p
  -#DONE added params[:id] to request
  .btn-group
    = button_to "Añadir Factura", new_debt_path, :class => "btn btn-large btn-primary", :method => 'get', params: {debtor_id: @debtor.id}        
%div
  %h5
    %strong
      = "Facturas:" if @debtor.respond_to?(:debts) && !@debtor.debts.blank?
  .col-md-8
    = render @debtor.debts