config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'
  
  match '/help',          to: 'static_pages#help',    via: 'get'
  match '/home',          to: 'static_pages#home',    via: 'get'
  match '/dev',           to: 'static_pages#dev',     via: 'get'
  match 'debtor/search',  to: 'debtors#search',       via: 'get', as: 'search'
  
  match '/import',        to: 'import#create',        via: 'post'
  match '/import',        to: 'import#new',           via: 'get'
  match '/import/status', to: 'import#status',        via: 'get'
  
  match '/email',         to: 'debts#preview_email',  via: 'get'
  match '/email/send',    to: 'debts#send_email',     via: 'post' 

  resources :debtors 
  resources :debts, except: :destroy do 
    resources :mail_logs, except: :destroy
  end

  match '/letter',        to: 'static_pages#modeloSC_724', via: 'get'
  
  

end

app/models/debt.rb
# -*- encoding : utf-8 -*-

# rubocop:disable Metrics/LineLength
class Debt < ActiveRecord::Base # TODO: create migration to prevent nulls on originating debt
  ## Hooks
  belongs_to :debtor, touch: true
  has_many :mail_logs, dependent: :restrict_with_exception
  # Dependend Destroy means:
  # if Debtor is erase so are all the debts associeated with.

  ## REGEX
  VALID_NUM_REGEX = /\A[[:digit:]]+\.?[[:digit:]]*\z/
  VALID_PERMIT_REGEX = \
    /\A[[:alpha:]]{2}-?[[:alpha:]]{2}-?[0-9]{2}-?[0-9]{2}-?[0-9]{2}-?[0-9]{1}\z/i
  VALID_INFRACTION_REGEX = /\A[[:alpha:]]-?[0-9]{2}-?[0-9]{2}-?[0-9]{3}-?[[:alpha:]]{2}\z/i
  VALID_PERMIT_OR_INFRACTION_REGEX = \
    /\A([[:alpha:]]{2}-?[[:alpha:]]{2}-?[0-9]{2}-?[0-9]{2}-?[0-9]{2}-?[0-9]{1})|([[:alpha:]]-?[0-9]{2}-?[0-9]{2}-?[0-9]{3}-?[[:alpha:]]{2})\z/i
  VALID_DATE_REGEX = \
    %r~\A([0-9]{1,2}(\/?|-?)[0-9]{1,2}(\/?|-?)[0-9]{4}|[0-9]{4}(\/?|-?)[0-9]{1,2}(\/?|-?)[0-9]{1,2})\z~
  VALID_ROUTING_NUM_REGEX = /(\A\z|\A[0-9]{9}\z)/

  ## Validations
  validates :debtor_id,          presence: true
  validates :original_debt_date, presence: true, format: { with: VALID_DATE_REGEX,
                                                           message: 'Debe ser una fecha.' }
  validates :amount_owed_pending_balance,        format: { with: VALID_NUM_REGEX,
                                                           message: 'Debe ser un número.' }
  validates :bounced_check_number,               format: { with: /\A[[:digit:]]*\z/i,
                                                           message: 'Debe ser un número.' }
  validates :permit_infraction_number,           format: { with: VALID_PERMIT_OR_INFRACTION_REGEX,
                                                           message: 'Debe ser un número de multa o permiso (o estar en blanco).' },
                                                 unless: proc { |debt_ex| debt_ex.permit_infraction_number.blank? }
  validates :bank_routing_number,                format: { with: VALID_ROUTING_NUM_REGEX,
                                                           message: 'Deber ser un número de nueve (9) digitos o estar en blanco.' }

  ## Methods
  def find_debtor_attr(debtor_id, attributes)
    result = []
    attributes.each do |attribute|
      attribute_clean = { name: :name, contact: :contact_person }.fetch(attribute)
      debtor = Debtor.find_by_id(debtor_id)
      result << (debtor.nil? ? 'NULL' : debtor.public_send(attribute_clean))
    end
    result
  end

  ## Export to CSV
  ## Calls to_plan_csv w/ correct options
  def self.to_csv(_options = {})
    to_plain_csv(%i[debtor_name contact_person]) do |extra_items, record|
      extra_items.push(record.find_debtor_attr(record.attributes['debtor_id'], %i[name contact]))
    end
  end

  ## Export to Plain CSV.
  def self.to_plain_csv(extra_column_names = [], options = {}, &block)
    require 'csv'
    CSV.generate(options) do |csv|
      csv.add_row(column_names + extra_column_names)
      all.each do |record|
        extra_items = []
        yield(extra_items, record) if block
        csv.add_row record.attributes.values_at(*column_names).concat(extra_items).flatten
      end
    end
  end
end

app/controllers/debts_controller.rb
# -*- encoding : utf-8 -*-

require 'mail_support'

# rubocop:disable Metrics/ClassLength
class DebtsController < ApplicationController
  before_action :authenticate_user! ## for DEVISE
  include MailSupport

  ## Resource Actions ##
  def new
    assign_current_user
    @debtor = Debtor.find_by_id(params[:debtor_id])
    @debt = Debt.new
  end

  def edit
    assign_current_user
    @debt = Debt.find_by_id(params[:id])
    @debtor = Debtor.find_by_id(@debt.debtor_id)
  end

  def show
    assign_current_user
    @debt = Debt.find_by_id(params[:id])
    @debtor = Debtor.find_by_id @debt.debtor_id
  end

  def create
    assign_current_user
    @debtor = Debtor.find_by_id(params[:debtor_id])
    fail if @debtor.nil?
    params[:debt][:debtor_id] = @debtor.id
    @debt = Debt.new(debt_params)
    @debt.permit_infraction_number = strip_hyphens(@debt.permit_infraction_number)
    @debt.originating_debt_amount = @debt.amount_owed_pending_balance
    if @debt.save
      flash[:success] = 'Nueva Factura Creada'
      redirect_to @debt
    else
      flash[:error] = 'Factura No Gravada'
      render 'new'
    end
  end

  def update
    assign_current_user
    @debt = Debt.find_by_id(params[:id])
    @debtor = Debtor.find_by_id(@debt.debtor_id)
    @debt.permit_infraction_number = strip_hyphens(@debt.permit_infraction_number)
    if @debt.update_attributes(update_debt_params) && @debt.valid?
      flash[:success] = 'Factura Actualizada'
      redirect_to @debt
    else
      flash[:error] = 'Factura No Actualizada'
      render 'edit'
    end
  end

  ## Index ##
  #  Index of all debt and XLS & CSV export
  #  Responds to xls and csv format and uses pagination
  def index
    assign_current_user
    case params['format']
    when 'csv', 'xls', 'xlsx'
      @debts_all = Debt.all
    else
      @debts_all = Debt.paginate(page: params[:page], per_page: 10)
    end
    respond_to do |format|
      format.html
      format.xls
      format.xlsx
      format.csv { send_data @debts_all.to_csv }
    end
  end

  ## Emails ##
  def preview_email
    @debt = Debt.find_by_id(mailer_params[:id])
    @user = current_user
    @mailer = mailer_params[:mailer].to_sym
    @date_first_email_sent = date_first_email_sent(@debt)
    @print = mailer_params[:print] == 'true' ? true : false
    prepare_email(@debt, @user, @mailer, preview: true,
                                         date_first_email_sent: @date_first_email_sent,
                                         display_attachments: false)
    render layout: false
  end

  def send_email # should be Post only
    @debt = Debt.find_by_id(mailer_params[:id])
    @user = current_user
    @mailer = mailer_params[:mailer].to_sym
    @date_first_email_sent = date_first_email_sent(@debt)
    prepare_email(@debt, @user, @mailer, send: true,
                                         date_first_email_sent: @date_first_email_sent,
                                         display_attachments: true)

    redirect_to @debt
  end

  private

  ## Controller Private Methods ##
  def assign_current_user
    @user = current_user
  end

  def mailer_params
    if user_signed_in? # Devise
      # If only used for sending can validate user role
      params.permit(
        :mailer,
        :id,
        :print
      )
    else
      flash[:error] = 'Usuario No autorizado.'
      redirect_to :back
    end
  end

  def debt_params
    if user_signed_in? # updated for Devise
      # Can be determined by role
      params.require(:debt).permit(
        :permit_infraction_number,
        :amount_owed_pending_balance,
        :paid_in_full,
        :type_of_debt,
        :original_debt_date,
        :originating_debt_amount,
        :bank_routing_number,
        :bank_name,
        :bounced_check_number,
        :in_payment_plan,
        :in_administrative_process,
        :contact_person_for_transactions,
        :notes,
        :debtor_id,
        :fimas_project_id,
        :fimas_budget_reference,
        :fimas_class_field,
        :fimas_program,
        :fimas_fund_code,
        :fimas_account
      )
    else
      redirect_to new_user_session_path
    end
  end

  def update_debt_params
    if user_signed_in? # updated for Devise
      # Can be determined by role
      params.require(:debt).permit(
        :permit_infraction_number,
        :amount_owed_pending_balance,
        :paid_in_full,
        :type_of_debt,
        :bank_routing_number,
        :bank_name,
        :bounced_check_number,
        :in_payment_plan,
        :in_administrative_process,
        :contact_person_for_transactions,
        :notes
      )
    else
      redirect_to new_user_session_path
    end
  end
end

app/helpers/debts_helper.rb
# -*- encoding : utf-8 -*-

module DebtsHelper
end

app/views/debts/_debt.html.haml
%li.grey
  %strong
    =link_to ("<span class='glyphicon glyphicon-folder-open'></span> ".html_safe + "#{number_to_currency debt.amount_owed_pending_balance, :unit => '$'}"), debt_path(debt.id)
  %span
    %li.light-grey.round-top-corners  
      %em Banco emitidor del cheque:
      = "#{debt.bank_name}"
    %li.light-grey
      %em Número del cheque devuelto: 
      = "#{debt.bounced_check_number}"
    %li.light-grey
      %em Notas: 
      = " #{debt.notes}"
    %li{:class => '#{red_green_yellow_grey_tag(@debt)} round-bottom-corners'}
      %em Pagada?
      = " #{debt.paid_in_full? ? 'si' : 'no'} "

app/views/debts/_list_all_debts.html.haml
%tr
  %td
    =link_to debt.id, debt_path(debt.id)
  %td
    =link_to "#{number_to_currency debt.amount_owed_pending_balance, :unit => '$'}", debt_path(debt.id)
  %td
    =I18n.l debt.original_debt_date, :format => '%d de %B de %Y'
  %td
    =link_to debt.debtor.name, debtor_path(debt.debtor.id)

app/views/debts/edit.html.haml
- provide(:title, "Editar Factura")
%h1.col-md-offset-2 Editar Factura
.row
  -if @debt.errors.any?
    %p.col-md-8.col-md-offset-2
      %strong
        Problemas con:
    - @debt.errors.full_messages.each do |msg|
      %li{:class => 'alert alert-danger col-md-8 col-md-offset-2'}
        = msg
  /
  %div{:class => "col-md-8 col-md-offset-2"}
    =#form_for(@debt, url: {params: {debtor_id: @debtor.id, id: @debt.id}, controller: :debts, action: :create} ) do |f|
    =form_for(@debt, :method => 'patch') do |f|
      = render partial: 'layouts/error_messages', :locals => { :object => f.object }
      =f.label :permit_infraction_number, "Número de Permisno o Multa"
      =f.text_field :permit_infraction_number, class: 'form-control'
      =f.label :amount_owed_pending_balance, "Cantidad debida"
      =f.number_field :amount_owed_pending_balance, class: 'form-control'  
      =#f.label :original_debt_date, "Fecha de la deuda originadora"
      =#f.date_field :original_debt_date, class: 'form-control datepicker' 
      =#f.label :bounced_check_bank, "Nombre del banco del cheque devuelto"
      =#f.text_field :bounced_check_bank
      =f.label :bounced_check_number, "Número del cheque devuelto"
      =f.number_field :bounced_check_number, class: 'form-control'
      =f.label :notes, "Notas"
      =f.text_field :notes, class: 'form-control'
      =#hidden_field(:debtor_id,@debtor.id)
      =#check_box_tag "en plan de pago?", "0", @debt.payment_plan?
      .btn-group
        =f.submit "Editar Factura", class: "btn btn-large btn-primary"

app/views/debts/index.html.haml
-#coding: utf-8
- provide(:title, "Facturas")
.row
  %h1 Facturas:
.row
  %aside.span6
    %section
      %h3
        Archivos de todas las facturas:
      %a{:href => "#{url_for debts_path(format: 'xlsx')}", :class => "btn btn-info"}
        Bajar datos en Excel
      %a{:href => "#{url_for debts_path(format: 'xls')}", :class => "btn btn-info"}
        Bajar datos en xls (LibreOffice)
      %a{:href => "#{url_for debts_path(format: 'csv')}", :class => "btn btn-info"}
        Bajar datos en CSV
.row
  %aside.span6
    %section
      %h3
        Listado:
      /Use a table here
      %table{:class => "table table-bordered table-striped table-hover table-condensed"}
        %th{:class => "table-header" } 
          ID
        %th
          Cantidad
        %th
          Fecha
        %th
          Nombre  
        -@debts_all.each do |debt_item|
          = render partial: 'list_all_debts', :locals => { :debt => debt_item }
        = will_paginate(@debts_all)
        /
.row
  %aside.span6
    %section
      %a{href: "/import", class: "btn btn-default alert-info"}
        Importar CSV

app/views/debts/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Facturas">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">permit_infraction_number</Data></Cell>
        <Cell><Data ss:Type="String">amount_owed_pending_balance</Data></Cell>
        <Cell><Data ss:Type="String">paid_in_full</Data></Cell>
        <Cell><Data ss:Type="String">type_of_debt</Data></Cell>
        <Cell><Data ss:Type="String">date_of_original_debt_date</Data></Cell>
        <Cell><Data ss:Type="String">originating_debt_amount</Data></Cell>
        <Cell><Data ss:Type="String">debtor_id</Data></Cell>
        <Cell><Data ss:Type="String">debtor_name</Data></Cell>
        <Cell><Data ss:Type="String">in_payment_plan</Data></Cell>
        <Cell><Data ss:Type="String">contact_person_for_transactions</Data></Cell>
        <Cell><Data ss:Type="String">notes</Data></Cell>
        <Cell><Data ss:Type="String">created_at</Data></Cell>
        <Cell><Data ss:Type="String">updated_at</Data></Cell>
        <Cell><Data ss:Type="String">fimas_project_id</Data></Cell>
        <Cell><Data ss:Type="String">fimas_budget_reference</Data></Cell>
        <Cell><Data ss:Type="String">fimas_class_field</Data></Cell>
        <Cell><Data ss:Type="String">fimas_program</Data></Cell>
        <Cell><Data ss:Type="String">fimas_fund_code</Data></Cell>
        <Cell><Data ss:Type="String">fimas_account</Data></Cell>
        <Cell><Data ss:Type="String">fimas_id</Data></Cell>
      </Row>
    <% @debts_all.each do |factura| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= factura.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.permit_infraction_number %></Data></Cell>
        <Cell><Data ss:Type="Currency"><%= factura.amount_owed_pending_balance %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.paid_in_full %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.type_of_debt %></Data></Cell>
        <Cell><Data ss:Type="Date"><%= factura.original_debt_date %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.originating_debt_amount  %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= factura.debtor_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.find_debtor_attr(factura.debtor_id, [:name]) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.in_payment_plan %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.contact_person_for_transactions %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.notes %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.created_at %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.updated_at %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.fimas_project_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.fimas_budget_reference %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.fimas_class_field %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.fimas_program %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.fimas_fund_code %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.fimas_account %></Data></Cell>
        <Cell><Data ss:Type="String"><%= factura.fimas_id %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/debts/new.html.haml
- provide(:title, "Crear Factura Nueva")
%h1.col-md-offset-2 Crear Una Nueva Factura
.row
  -if @debt.errors.any?
    %p.col-md-8.col-md-offset-2
      %strong
        Problemas con:
    - @debt.errors.full_messages.each do |msg|
      %li{:class => 'alert alert-danger col-md-8 col-md-offset-2'}
        = msg
  /
  %h3.col-md-8.col-md-offset-2
    %strong
      = "Añadir una factura a: "
    %p
    - if @debtor 
      %em.grey
        !=" &bull;"
        = @debtor.name
      %em
        = @debtor.tel
        = "  |  "
        = @debtor.contact_person
        %br
        = "EIN: #{@debtor.employer_id_number}"
        %br
        = "Ultimos 4 de SS: #{@debtor.ss_last_four}"
    / 
  %br
  %div{:class => "col-md-8 col-md-offset-2"}
    - if @debtor.blank?
      -#Searchform
    -else     
      =form_for(@debt, url: {params: {debtor_id: @debtor.id}, controller: :debts, action: :create} ) do |f|
        -#render partial: 'layouts/error_messages', :locals => { :object => f.object }
        =f.label :permit_infraction_number, "Número de Permisno o Multa"
        =f.text_field :permit_infraction_number, class: 'form-control', placeholder: 'ex. PG-GE-71-12-10-4 o M-12-12-050-RC'
        =f.label :original_debt_date, "Fecha de la deuda originadora"
        =f.date_field :original_debt_date, class: 'form-control datepicker date_field', placeholder: '1999-01-31'
        =f.label :amount_owed_pending_balance, "Cantidad debida"
        .input-group
          %span.input-group-addon
            ='$'
          =f.number_field :amount_owed_pending_balance, class: 'form-control'
          %span.input-group-addon
            = '.00'   
        =#f.label :bounced_check_bank, "Nombre del banco del cheque devuelto"
        =#f.text_field :bounced_check_bank
        =f.label :bounced_check_number, "Número del cheque devuelto"
        =f.number_field :bounced_check_number, class: 'form-control'
        =f.label :notes, "Notas"
        =f.text_field :notes, class: 'form-control'
        =#f.label :fimas_id, "Número de Fimas"
        =#f.number_field :fimas_id, class: 'form-control'
        =f.label :fimas_project_id
        =f.text_field :fimas_project_id, class: 'form-control'
        =f.label :fimas_budget_reference
        =f.text_field :fimas_budget_reference, class: 'form-control'
        =f.label :fimas_class_field
        =f.text_field :fimas_class_field, class: 'form-control'
        =f.label :fimas_program
        =f.text_field :fimas_program, class: 'form-control'
        =f.label :fimas_fund_code
        =f.text_field :fimas_fund_code, class: 'form-control'
        =f.label :fimas_account
        =f.text_field :fimas_account, class: 'form-control'
        =#hidden_field(:debtor_id,@debtor.id)
        =#check_box_tag "en plan de pago?", "0", @debt.payment_plan?
        .btn-group
          =f.submit "Crear Factura", class: "btn btn-large btn-primary"
    /end  

app/views/debts/preview_email.html.haml
:css
  .btn {
    border-radius: 4px;
    border-style: solid;
    border-width: 1px;
    border-color: rgba(0,0,0,0)
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-size: 14px;
    height: 34px;
    cursor: pointer;
  }

- flash.each do |k, v|
  %div{:class => "alert alert-#{k}"}= v
- unless @print#
  %span{:class => 'glyphicon glyphicon-envelope'}
    = button_to "Enviar", email_send_path, :class => "btn btn-large btn-primary", :method => :post, params: { id: @debt.id, mailer: @mailer, user_id: @user.id }
  %span{:class => 'glyphicon glyphicon-print'}
    = button_to "Preparar para Imprimir", email_path, form: {:target => "_blank"}, :class => "btn btn-large btn-primary", :method => :get, params: { id: @debt.id, mailer: @mailer, user_id: @user.id, print: 'true' }
  %hr
  = @mail_preview.header.to_s if @mail_preview
  %hr
/
- if @mail_preview  
  - unless @mail_preview.multipart? 
    = @mail_preview.body.to_s.html_safe 
  - else
    = @mail_preview.html_part.body.to_s.html_safe #@mail_preview.parts[0].body.to_s.html_safe
  /
/

app/views/debts/show.html.haml
-#coding: utf-8
- provide(:title, "Record de la Factura")
%h1 Factura:
.row
  %aside.col-md-6
    %section
      %h5
        -if @debtor
          %ol.microposts
            = render @debt #render partial: 'debts', :locals => { :collection => @collection }   
          %em Deudor:            
          = link_to @debtor.name, @debtor
          ="   |  Persona Contacto: "
          = @debtor.contact_person
        /end  

  %aside.col-md-4
    .btn-group-vertical.btn-group
      =#yield :logs_sidebar
      -# %a{:href => '#{url_for new_payment_plan_path(@debt)}', :class => "btn btn-primary disabled"}
      -#  Añadir Plan de Pago
      = button_to "Generar Primer Aviso", email_path, :class => "btn btn-primary", :method => :get, params: {id: @debt.id, mailer: :first} 
      = button_to "Generar Segundo Aviso", email_path, :class => "btn btn-primary", :method => :get, params: {id: @debt.id, mailer: :second}
      / %span{:class => 'glyphicon glyphicon-envelope'}
      = button_to "Generar Tercer Aviso", email_path, :class => "btn btn-primary", :method => :get, params: {id: @debt.id, mailer: :third}
      /= link_to "Vista preliminar de todos los Emails", rails_email_preview.rep_emails_url(email_locale: 'es', debt_id: @debt.id, current_user: @user)
.row
  -if @debt.respond_to?(:mail_logs) && !@debt.mail_logs.blank?
    %table.table.table-stripped
      %thead
        %th
          Enviado el:
        %th
          Email Enviado:
      = render @debt.mail_logs