config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'
  
  match '/help',          to: 'static_pages#help',    via: 'get'
  match '/home',          to: 'static_pages#home',    via: 'get'
  match '/dev',           to: 'static_pages#dev',     via: 'get'
  match 'debtor/search',  to: 'debtors#search',       via: 'get', as: 'search'
  
  match '/import',        to: 'import#create',        via: 'post'
  match '/import',        to: 'import#new',           via: 'get'
  match '/import/status', to: 'import#status',        via: 'get'
  
  match '/email',         to: 'debts#preview_email',  via: 'get'
  match '/email/send',    to: 'debts#send_email',     via: 'post' 

  resources :debtors 
  resources :debts, except: :destroy do 
    resources :mail_logs, except: :destroy
  end

  match '/letter',        to: 'static_pages#modeloSC_724', via: 'get'
  
  

end

app/views/layouts/_error_messages.html.haml
-if false && @user.errors.any?
  #error_explanation
    %div{:class => "alert alert-error"}
      %i.icon-warning-sign
      ="Hay #{ pluralize(@user.errors.count, 'error')}"
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= "* #{msg}"
/
-if !object.nil? && object.errors.any?
  #error_explanation
    %div{:class => "alert alert-error"}
      ="Hay #{ pluralize(object.errors.count, 'error')}"
    %ul
      - object.errors.full_messages.each do |msg|
        %li= "* #{msg}"
/

app/views/layouts/_footer.html.haml
%footer.footer
  %nav
    %ul
      %li
        -#TODO REFACTOR##########################
        -# "grupo: #{ current_user.nil? ? 'ninguno' : '' }"
      %li
        = "usuario actual: #{ current_user.nil? ? 'ninguno' : current_user.email }"
      %li
        = link_to '<span class="glyphicon glyphicon-question-sign"></span> Ayuda'.html_safe, help_path
      %li
        = link_to "Usuario Nuevo", new_user_registration_path
      

app/views/layouts/_glyphicons.html.haml
:css
  @font-face { font-family: 'Glyphicons Halflings';   
  src: url(#{asset_path 'glyphicons-halflings-regular.eot'});   
  src: url(#{asset_path 'glyphicons-halflings-regular.eot?#iefix'}) format('embedded-opentype'), 
  url(#{asset_path 'glyphicons-halflings-regular.woff'}) format('woff'),  
  url(#{asset_path 'glyphicons-halflings-regular.ttf'}) format('truetype'), 
  url(#{asset_path 'glyphicons-halflings-regular.svg#glyphicons-halflingsregular'}) format('svg'); } 

app/views/layouts/_header.html.haml
%header{ :class => 'navbar navbar-default navbar-fixed-top0 navbar-inverse round-bottom-corners', :role => 'navigation' }
  .container-fluid
    .navbar-header
      =link_to "Rukh", home_path, id: "logo", class: 'navbar-brand'
    .collapse.navbar-collapse
      .nav.navbar-nav.navbar-right
        %ul{ :class => 'nav navbar-nav' }
          -if signed_in?
            -# %li= link_to "Lista de Deudores", debtors_path
            %li= link_to "Facturas", debts_path
            %li= link_to "Deudor Nuevo", new_debtor_path
            %li= link_to "Buscar Deudor", search_path
            %li= link_to "Log out", destroy_user_session_path, method: "delete"    
            %li.dropdown
              %a{:href => '#', :class => 'dropdown-toggle', :'data-toggle' => 'dropdown' }
                Usuario
                %b.caret
              %ul.dropdown-menu
                %li= link_to "#{@user.email if @user}", '#'
                %li.divider
                -# %li= link_to "Información del Usuario", current_user #Unavailabe in Devise
                -# %li= link_to "Los Usuarios", users_path              #Unavailabe in Devise
                %li= link_to "Actualizar Información", edit_user_registration_path(current_user)
                %li.divider
                %li= link_to "Log out", destroy_user_session_path, method: "delete"
          -else
            %li= link_to "Log in", new_user_session_path #'/login'
 

app/views/layouts/_shim.html.haml
/[if lt IE 9] <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rukh</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ :charset => 'utf-8' }
    %title
      = "Rukh | #{yield :title}"
    = csrf_meta_tags      
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    -# favicon_link_tag(asset_path('favicon.ico'))
    = favicon_link_tag('favicon.ico')
    = render 'layouts/shim'
    = render 'layouts/glyphicons'
  %body  
    = render 'layouts/header'
    .container
      - flash.each do |k, v|
        - notice_hash = {'error' => 'danger', 'notice' => 'info', 'success' => 'success'}
        %div{:class => "alert alert-#{notice_hash.fetch(k, 'warning')} #{k}"}= v
      =yield
      = render 'layouts/footer'
      =debug(params) if Rails.env.development?
      -#TODO:  Move to .coffee file 
      :coffee
        if navigator.userAgent.indexOf('compatible') > -1
          alert "Tiene el modulo de compatibilidad prendido en IE, la navegación no funcionará. Por favor apague el modulo. Vaya a el ícono de una rueda dentada y seleccione 'Compatibility View Settings'"
          $('.container').prepend("<div class='alert alert-danger'> IE Compatibilty Turned On. Please turn off.</div>")